In [1]:
import pandas as pd
import numpy as np
import joblib
import requests

from datetime import datetime

In [2]:
model = joblib.load("../models/lightgbm_model.pkl")

scaler = joblib.load("../models/scaler.pkl")

language_encoder = joblib.load("../models/language_encoder.pkl")

license_encoder = joblib.load("../models/license_encoder.pkl")

adoption_encoder = joblib.load("../models/adoption_encoder.pkl")

print("All files loaded successfully!")

All files loaded successfully!

In [5]:
repo_url = "https://github.com/Prajith3027/drowsiness-detection"

print("Repository URL:", repo_url)

print("Repository URL:", repo_url)

Repository URL: https://github.com/Prajith3027/drowsiness-detection
Repository URL: https://github.com/Prajith3027/drowsiness-detection

In [6]:
# Extract owner and repository name
parts = repo_url.strip("/").split("/")

owner = parts[-2]
repo = parts[-1]

# Create GitHub API URL
api_url = f"https://api.github.com/repos/{owner}/{repo}"

# Fetch repository details
response = requests.get(api_url)

# Check if the repository exists
if response.status_code == 200:
    repo_data = response.json()
    print("✅ Repository found!")
else:
    print("❌ Repository not found!")

✅ Repository found!

In [7]:
from datetime import datetime

# Basic repository information
language = repo_data["language"] if repo_data["language"] else "Unknown"

forks = repo_data["forks_count"]

open_issues = repo_data["open_issues_count"]

size_kb = repo_data["size"]

description = repo_data["description"] or ""

description_length = len(description)

license_name = (
    repo_data["license"]["name"]
    if repo_data["license"] is not None
    else "No License"
)

# Date information
created_at = datetime.strptime(
    repo_data["created_at"],
    "%Y-%m-%dT%H:%M:%SZ"
)

pushed_at = datetime.strptime(
    repo_data["pushed_at"],
    "%Y-%m-%dT%H:%M:%SZ"
)

created_year = created_at.year

pushed_year = pushed_at.year

project_age_days = (datetime.now() - created_at).days

days_since_last_push = (datetime.now() - pushed_at).days

In [8]:
contributors = 0
page = 1

while True:

    contributors_url = (
        f"https://api.github.com/repos/{owner}/{repo}/contributors"
        f"?per_page=100&page={page}"
    )

    response = requests.get(contributors_url)

    data = response.json()

    if len(data) == 0:
        break

    contributors += len(data)

    page += 1

print("Total Contributors:", contributors)

Total Contributors: 1

In [9]:
print("Language:", language)
print("Forks:", forks)
print("Open Issues:", open_issues)
print("Contributors:", contributors)
print("Size (KB):", size_kb)
print("License:", license_name)
print("Description Length:", description_length)
print("Created Year:", created_year)
print("Pushed Year:", pushed_year)
print("Project Age (Days):", project_age_days)
print("Days Since Last Push:", days_since_last_push)

Language: Python
Forks: 0
Open Issues: 0
Contributors: 1
Size (KB): 3258
License: No License
Description Length: 0
Created Year: 2026
Pushed Year: 2026
Project Age (Days): 68
Days Since Last Push: 68

In [10]:
# Create a dictionary of features
repo_features = {
    "language": language,
    "forks": forks,
    "open_issues": open_issues,
    "contributors": contributors,
    "size_kb": size_kb,
    "license": license_name,
    "project_age_days": project_age_days,
    "days_since_last_push": days_since_last_push,
    "description_length": description_length,
    "created_year": created_year,
    "pushed_year": pushed_year
}

# Convert to DataFrame
new_repo_df = pd.DataFrame([repo_features])

new_repo_df

,language,forks,open_issues,contributors,size_kb,license,project_age_days,days_since_last_push,description_length,created_year,pushed_year
0,Python,0,0,1,3258,No License,68,68,0,2026,2026

In [11]:
new_repo_df["language"] = language_encoder.transform(
    new_repo_df["language"]
)

new_repo_df["license"] = license_encoder.transform(
    new_repo_df["license"]
)

new_repo_df

,language,forks,open_issues,contributors,size_kb,license,project_age_days,days_since_last_push,description_length,created_year,pushed_year
0,4,0,0,1,3258,30,68,68,0,2026,2026

In [13]:
new_repo_df["language"] = language_encoder.transform(
    new_repo_df["language"]
)

new_repo_df["license"] = license_encoder.transform(
    new_repo_df["license"]
)

new_repo_df

ValueError: y contains previously unseen labels: 4

In [14]:
new_repo_df

,language,forks,open_issues,contributors,size_kb,license,project_age_days,days_since_last_push,description_length,created_year,pushed_year
0,4,0,0,1,3258,30,68,68,0,2026,2026

In [15]:
print(new_repo_df["language"])
print(new_repo_df["license"])

0    4
Name: language, dtype: int64
0    30
Name: license, dtype: int64

In [16]:
language_encoder

LabelEncoder()

In [17]:
license_encoder

LabelEncoder()

In [18]:
import joblib

model = joblib.load("../models/lightgbm_model.pkl")
scaler = joblib.load("../models/scaler.pkl")
language_encoder = joblib.load("../models/language_encoder.pkl")
license_encoder = joblib.load("../models/license_encoder.pkl")
adoption_encoder = joblib.load("../models/adoption_encoder.pkl")

print("All files loaded successfully!")

All files loaded successfully!

In [19]:
new_repo_df

,language,forks,open_issues,contributors,size_kb,license,project_age_days,days_since_last_push,description_length,created_year,pushed_year
0,4,0,0,1,3258,30,68,68,0,2026,2026

In [20]:
print(new_repo_df)

   language  forks  open_issues  contributors  size_kb  license  \
0         4      0            0             1     3258       30

   project_age_days  days_since_last_push  description_length  created_year  \
0                68                    68                   0          2026

   pushed_year
0         2026

In [21]:
print(new_repo_df["language"])
print(new_repo_df["license"])

0    4
Name: language, dtype: int64
0    30
Name: license, dtype: int64

In [22]:
new_repo_scaled = scaler.transform(new_repo_df)

print(new_repo_scaled)

[[ 0.94289187 -0.295697   -0.27880738 -0.44634829 -0.08904424  0.8878121
  -2.84507994 -0.76492592 -0.20276711  3.27236295  1.25516318]]

In [23]:
prediction = model.predict(new_repo_scaled)

probability = model.predict_proba(new_repo_scaled)

prediction_label = adoption_encoder.inverse_transform(prediction)

confidence = probability.max() * 100

print("Prediction :", prediction_label[0])
print(f"Confidence : {confidence:.2f}%")

c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Prediction : Low Adoption
Confidence : 99.96%

c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [24]:
new_repo_scaled = scaler.transform(new_repo_df)

prediction = model.predict(new_repo_scaled)

probability = model.predict_proba(new_repo_scaled)

prediction_label = adoption_encoder.inverse_transform(prediction)

confidence = probability.max() * 100

print("Prediction :", prediction_label[0])
print(f"Confidence : {confidence:.2f}%")

Prediction : Low Adoption
Confidence : 99.96%

c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(